services:
  backend:
    build:
      context: ./repo/the-fool
      dockerfile: Dockerfile
    container_name: the-fool
    environment:
      PORT: 6000
      USE_TLS: false
    ports:
      - 6000:6000
  frontend:
    build:
      context: ./repo/the-magician
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_HOST: "${HOSTNAME}/ws/"
        NEXT_PUBLIC_SECURE_CONNECTION: "false"
        NEXT_PUBLIC_SOUNDPATH: "/sound/se"
        NEXT_PUBLIC_IMAGE_SELF_HOSTING: "false"
        NEXT_PUBLIC_IMAGE_SIZE: "normal"
    environment:
      DISABLE_DISCORD_LOGIN: "true"
      DISABLE_SUPABASE: "true"
    container_name: the-magician
    ports:
      - 4000:3000
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - $PORT:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
